-- Flight Log baseline schema.
--
-- This script is the canonical schema. Hibernate is set to ddl-auto=validate,
-- so any future entity change requires a new V<N>__*.sql file in this folder.
--
-- Idempotent (CREATE ... IF NOT EXISTS) so it can also be applied safely to
-- databases that were originally created by Hibernate ddl-auto=update.

-- =========================================================================
-- TABLES
-- =========================================================================

CREATE TABLE IF NOT EXISTS addresses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city        VARCHAR(255),
    country     VARCHAR(255),
    postal_code VARCHAR(255),
    street      VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS airplane_types (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_capacity INTEGER NOT NULL,
    type         VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS club_airplanes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive           BOOLEAN NOT NULL,
    immatriculation   VARCHAR(255),
    airplane_type_id  BIGINT REFERENCES airplane_types(id)
);

CREATE TABLE IF NOT EXISTS airplanes (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category                        VARCHAR(255) CHECK (category IN ('GLIDER', 'POWERED')),
    guest_airplane_immatriculation  VARCHAR(255),
    guest_airplane_type             VARCHAR(255),
    club_airplane_id                BIGINT REFERENCES club_airplanes(id)
);

CREATE TABLE IF NOT EXISTS persons (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(255),
    last_name   VARCHAR(255),
    member_id   BIGINT NOT NULL,
    person_type VARCHAR(255) CHECK (person_type IN ('ClubMember', 'Guest')),
    address_id  BIGINT UNIQUE REFERENCES addresses(id)
);

CREATE TABLE IF NOT EXISTS flights (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) WITH TIME ZONE,
    created_by        VARCHAR(255),
    landing_time      TIMESTAMP(6) WITH TIME ZONE,
    note              VARCHAR(255),
    start_type        VARCHAR(255) CHECK (start_type IN ('WINCH', 'TOW')),
    takeoff_time      TIMESTAMP(6) WITH TIME ZONE,
    task              VARCHAR(255),
    type              VARCHAR(255) CHECK (type IN ('Glider', 'Towplane')),
    updated_at        TIMESTAMP(6) WITH TIME ZONE,
    updated_by        VARCHAR(255),
    airplane_id       BIGINT REFERENCES airplanes(id),
    copilot_id        BIGINT REFERENCES persons(id),
    linked_flight_id  BIGINT REFERENCES flights(id),
    pilot_id          BIGINT REFERENCES persons(id)
);

CREATE TABLE IF NOT EXISTS flight_starts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    glider_flight_id    BIGINT REFERENCES flights(id),
    towplane_flight_id  BIGINT NOT NULL REFERENCES flights(id)
);

CREATE TABLE IF NOT EXISTS users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at            TIMESTAMP(6) WITH TIME ZONE,
    display_name          VARCHAR(100),
    email                 VARCHAR(254) NOT NULL UNIQUE,
    failed_login_attempts INTEGER      NOT NULL,
    locked_until          TIMESTAMP(6) WITH TIME ZONE,
    password_hash         VARCHAR(200) NOT NULL,
    role                  VARCHAR(20)  NOT NULL CHECK (role IN ('WRITER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumed_at  TIMESTAMP(6) WITH TIME ZONE,
    expires_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    token_hash   VARCHAR(100) NOT NULL UNIQUE,
    user_id      BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action      VARCHAR(60)  NOT NULL,
    details     OID,
    entity_id   BIGINT,
    entity_type VARCHAR(60),
    level       VARCHAR(10)  NOT NULL CHECK (level IN ('INFO', 'WARN', 'ERROR')),
    ts          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_email  VARCHAR(254),
    user_id     BIGINT
);

CREATE TABLE IF NOT EXISTS club_user_snapshot (
    member_id   BIGINT       NOT NULL PRIMARY KEY,
    fetched_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    first_name  VARCHAR(100),
    last_name   VARCHAR(100),
    roles       VARCHAR(200)
);

-- =========================================================================
-- INDEXES (also created by V2__indexes.sql; CREATE INDEX IF NOT EXISTS makes
-- both files idempotent and order-tolerant).
-- =========================================================================

CREATE INDEX IF NOT EXISTS idx_audit_ts            ON audit_log (ts);
CREATE INDEX IF NOT EXISTS idx_audit_user          ON audit_log (user_id);
CREATE INDEX IF NOT EXISTS idx_flights_takeoff_time ON flights (takeoff_time);
CREATE INDEX IF NOT EXISTS idx_flights_landing_time ON flights (landing_time);
